filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false
tools:
    php_cs_fixer:
        config: { level: psr2 }
    
