language: php

php:
  - nightly
  - hhvm
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  
install: composer install --no-interaction

before_script: composer dump-autoload

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - php vendor/bin/coveralls -v